version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - aws s3 sync ./build s3://krishan-portfiolio-site
  post_build:
    commands:
      - echo Deployed on `date`
